[package]
name = "img-optim"
version = "0.1.0"
authors = ["Mickaël <mleduque@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { git = "https://github.com/clap-rs/clap", tag = "v3.0.0-beta.2" }
glob = "0.3.0"
path-absolutize = "3.0.10"
tempfile = "3.2.0"
zip = "0.5.12"
zip-extensions = "0.6.0"
