[package]
name = "img-optim"
version = "0.1.0"
authors = ["Mickaël <mleduque@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { git = "https://github.com/clap-rs/clap", tag = "v3.0.0-beta.2" }
env_logger = "0.10.0"
globwalk = "0.8.1"
lazy_static = "1.4.0"
log = "0.4.17"
path-absolutize = "3.0.10"
tempfile = "3.2.0"
zip = "0.6.4"
